apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: porter-agent
    meta.helm.sh/release-namespace: porter-agent-system
  creationTimestamp: "2023-02-08T20:27:49Z"
  generation: 2
  labels:
    app: loki
    app.kubernetes.io/managed-by: Helm
    chart: loki-0.2.0
    heritage: Helm
    release: porter-agent
  name: porter-agent-loki
  namespace: porter-agent-system
  resourceVersion: "357125174"
  uid: 0e7008a2-5321-4c29-82c1-d34be9ab7af8
spec:
  podManagementPolicy: OrderedReady
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: loki
      release: porter-agent
  serviceName: porter-agent-loki-headless
  template:
    metadata:
      annotations:
        checksum/config: 4fa0c5fb36aa38c4d54e9818896040ea5a2dd9ad4439f351238f01e7e8c4d2f1
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: loki
        name: porter-agent-loki
        release: porter-agent
    spec:
      affinity: {}
      containers:
      - args:
        - -config.file=/etc/loki/loki.yaml
        image: grafana/loki:2.6.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: loki
        ports:
        - containerPort: 3100
          name: http-metrics
          protocol: TCP
        - containerPort: 9095
          name: grpc
          protocol: TCP
        - containerPort: 7946
          name: memberlist-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 3Gi
          requests:
            cpu: 600m
            memory: 3Gi
        securityContext:
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /etc/loki
          name: config
        - mountPath: /data
          name: storage
      dnsPolicy: ClusterFirst
      nodeSelector:
        porter.run/workload-kind: monitoring
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      serviceAccount: porter-agent-loki
      serviceAccountName: porter-agent-loki
      terminationGracePeriodSeconds: 4800
      tolerations:
      - effect: NoSchedule
        key: porter.run/workload-kind
        operator: Equal
        value: monitoring
      volumes:
      - emptyDir: {}
        name: tmp
      - name: config
        secret:
          defaultMode: 420
          secretName: porter-agent-loki
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 0
  replicas: 0
